# Generated by Django 4.2.20 on 2025-04-04 11:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities_icons/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Dishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_r', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('addresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('crée_le', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='establishments/')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordonnées GPS')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de téléphone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('location_hours', models.TextField(blank=True, null=True, verbose_name='Horaires')),
                ('amenities', models.ManyToManyField(blank=True, related_name='establishments', to='reviews.amenity')),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
            },
        ),
        migrations.CreateModel(
            name='EtablishmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Categorie d'établissement",
                'verbose_name_plural': "Categories d'établissement",
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='vibes_icons/')),
            ],
            options={
                'verbose_name': 'Ambiance',
                'verbose_name_plural': 'Ambiances',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('crée_le', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_reviews', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.establishment')),
                ('images', models.ManyToManyField(blank=True, related_name='reviews', to='reviews.image')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('reports', models.ManyToManyField(blank=True, related_name='reported_reviews', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du menu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menus/')),
                ('menu_pdf', models.FileField(blank=True, null=True, upload_to='menus_pdfs/')),
                ('dishes', models.ManyToManyField(blank=True, related_name='menus', to='reviews.dishe', verbose_name='Plats')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='reviews.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.etablishmentcategory'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishment',
            name='vibes',
            field=models.ManyToManyField(blank=True, related_name='establishments', to='reviews.vibe'),
        ),
        migrations.AddField(
            model_name='dishe',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='reviews.image'),
        ),
    ]
