# Generated by Django 4.2.20 on 2025-03-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-crée_le']},
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='address',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='created_at',
            new_name='crée_le',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='name',
            new_name='nom_r',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='city',
            new_name='ville',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='crée_le',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='establishment',
            new_name='etablissement',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
