# Generated by Django 4.2.20 on 2025-03-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='nom_r',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.establishment'),
        ),
    ]
