# Generated by Django 4.2.20 on 2025-03-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_establishment_nom_r_alter_review_etablissement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterField(
            model_name='establishment',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='nom_r',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.establishment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='note',
            field=models.IntegerField(),
        ),
    ]
