# Generated by Django 4.2.20 on 2025-03-17 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_alter_review_options_alter_establishment_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='categorie',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('fast-food', 'Fast Food'), ('cafe', 'Café'), ('bar', 'Bar'), ('autre', 'Autre')], max_length=50),
        ),
    ]
