# Generated by Django 4.2.20 on 2025-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/'),
        ),
    ]
