# Generated by Django 4.2.20 on 2025-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='menus_pdfs/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nom_plat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
