# Generated by Django 4.2.20 on 2025-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_menu_menu_pdf_alter_menu_image_alter_menu_nom_plat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nom_plat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
