# Generated by Django 4.2.20 on 2025-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_menu_nom_plat_alter_menu_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='location_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='popular_dishes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='vibe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
