# Generated by Django 4.2.20 on 2025-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_establishment_amenities_establishment_location_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='vibes_icons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='vibe',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='amenities',
        ),
        migrations.AddField(
            model_name='establishment',
            name='vibes',
            field=models.ManyToManyField(blank=True, related_name='establishments', to='reviews.vibe'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='establishments', to='reviews.amenity'),
        ),
    ]
