name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Utilise le runner local

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Déployer l’application
        run: |
          cd /var/www/eatwhere_app/Eatwhere
          git pull origin main
          source ../venv/bin/activate
          pip3 install -r requirements_prod.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          systemctl daemon-reload
          sudo systemctl restart eatwhere_gunicorn
          sudo systemctl restart nginx

